config:
  plugin:
    metrics-by-endpoint: {}
  target: 'http://localhost:3000'
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
  - name: 'Generate random user + create user'
    flow:
      - log: 'Generando un usuario nuevo aleatorio'
      - get:
          url: '/faker'
          capture:
            - json: "$.name"
              as: "name"
            - json: "$.lastname"
              as: "lastname"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: 'Creando el usario: {{ email }}'
      - post:
          url: '/api/users'
          json:
            name: "{{ name }}"
            lastname: "{{ lastname }}"
            email: "{{ email }}"
            password: "{{ password }}"